In [5]:
import numpy as np

# 用np代替numpy，让代码更简洁
a = [1, 2, 3, 4]  # 创建列表a
b = np.array([1, 2, 3, 4])  # 从列表a创建数组b，array就是数组的意思
print(a)
print(b)
print(type(a))
# 打印a的类型
print(type(b))  # 打印b的类型
print(a[1])
print(b[1])
print(a[0:2])
print(b[0:2])
c = a * 2
d = b * 2
print(c)
print(d)

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
2
2
[1, 2]
[1 2]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [6]:
e = [[1, 2], [3, 4], [5, 6]]  # 列表里的元素为小列表
f = np.array([[1, 2], [3, 4], [5, 6]])  # 创建二维数组的一种方式
print(e)
print(f)

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]
